source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'sqlite3'
gem 'coffee-rails', '~> 4.1.0'
gem 'active_model_serializers'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc


group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'

  gem 'spring'
end

